-- 8.1
CREATE TEMPORARY TABLE actor_276020 (
    actor_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    imię VARCHAR(45) NOT NULL,
    nazwisko VARCHAR(45) NOT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (actor_id)
);